Update cleanup-old-docker-images.yml

diff --git a/.github/workflows/cleanup-old-docker-images.yml b/.github/workflows/cleanup-old-docker-images.yml
--- a/.github/workflows/cleanup-old-docker-images.yml
+++ b/.github/workflows/cleanup-old-docker-images.yml
@@ -13,14 +13,15 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
-    - name: Set up Docker CLI
+    - name: Set up Docker CLI and jq
       run: |
         sudo apt-get update
         sudo apt-get install -y jq
 
-    - name: Login to Docker Hub
+    - name: Login to GitHub Container Registry
       uses: docker/login-action@v2
       with:
+        registry: ghcr.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
 
@@ -40,6 +41,13 @@ jobs:
           while true; do
             response=$(curl -s -H "Authorization: Bearer $token" "https://ghcr.io/v2/${repo}/tags/list?n=${per_page}&page=${page}")
             echo "Response: $response"  # Log the response for debugging
+
+            # Check if the response contains errors
+            if echo "$response" | jq -e '.errors' > /dev/null; then
+              echo "Error fetching tags: $(echo $response | jq '.errors')"
+              exit 1
+            fi
+
             new_tags=$(echo $response | jq -r '.tags | select(. != null) | .[]')
             
             if [ -z "$new_tags" ]; then
